### ISSUE TITLE
Replace Web3Connect with Onboard

### ISSUE THREAD

**Issue by ilinzweilin** [centrifuge/tinlake-ui#169]
We should update how we get a web3 provider by switching from web3connect to https://docs.blocknative.com/onboard This is used in gnosis safe and has by far the best user experience.

Acceptance Criteria:
1) It should work in Firefox, Chrome, Brave
2) It should support ledgers natively
3) It should support metamask & portis

**Comment by lucasvo** [comment]
Related to #297
