### ISSUE TITLE
[TBD] Add timeout before loan data is fetched from chain

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#213]
When repaying a loan, sometimes the loan state is not updated quickly enough on chain. While the transaction/repayment is successful, the UI then still displays the old values before repay.

**Comment by lucasvo** [comment]
I think a nice way to do this is to globally show a banner at the top of the page saying: 
"there are pending transactions. the page will be updated when the transaction is mined."

**Comment by philipstanislaus** [comment]
Retry instead of timeouts
