### ISSUE TITLE
investigate MetaMask error: header not found

### ISSUE THREAD

**Issue by ilinzweilin** [centrifuge/tinlake-ui#217]
`Uncaught (in promise) Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32000,"message":"header not found"}}'
    at commons.9ee1948002f9087f8ee9.js:1`

Error sometimes occurs.
Observed in tinlake-ui on issueLoan & loadLoan
also observed while using gnosis safe when loading safe

**Comment by charleenfei** [comment]
potentially same issue as: https://github.com/MetaMask/metamask-extension/issues/7234
