### ISSUE TITLE
Rename the label to all interest Fields to `Annual Interest Rate (APR)`

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#225]

**Comment by charleenfei** [comment]
also will fix this bug for invalid Eth address due to default investor address being an empty string:  ![Capture d’écran 2020-03-26 à 11.09.05.png](https://images.zenhubusercontent.com/5c37281270a1f951ec1a903a/9f2664e1-2d6a-4a18-9e48-82aa2902a0ca)
