### ISSUE TITLE
Pimp `redeem token` function

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#273]
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/22917a3a-e8ab-4a9d-9fad-3ed177ad12fb)
Add `max` button and show expected investment value

**Comment by lucasvo** [comment]
This should not be implemented until we have the new eth widgets in axis (https://github.com/centrifuge/axis/pull/54)

**Comment by lucasvo** [comment]
@acolytec3 are you implementing this with the new widget?

**Comment by acolytec3** [comment]
The messaging isn't in the new widget but the concept of setting a max amount is there with the "set max" button I built as part of the widget. It just looks a little different than what's in that mockup. I should be able to if the amount in DAI is available in the code today or can easily be derived.

**Comment by lucasvo** [comment]
Yes, you can ignore the message "You will receive in exchange" and take the design from the widgets we have. The design is outdated in this ticket.

@ilinzweilin how can the max be determined in the code today?

**Comment by ilinzweilin** [comment]
in the redeem container, you find the values tokenBalance and maxRedeemAmount. 
max is the smaller of these two values ->` min(tokenBalance, maxRedeemAmount)`
