### ISSUE TITLE
Loans list (home page) table breaks on safari

### ISSUE THREAD

**Issue by sounak98** [centrifuge/tinlake-ui#312]
The table for loans on the home page breaks on safari but gets rendered perfectly on firefox or google chrome.

## Screenshot
<img width="2032" alt="screenshot_2020-05-12_at_9 36 00_am" src="https://user-images.githubusercontent.com/22390515/81835807-4da0bc00-9560-11ea-9cb9-24a95ac0f63f.png">

**Comment by philipstanislaus** [comment]
@lucasvo can we have this as bounty ticket?
