### ISSUE TITLE
image and text description for Dashboard 

### ISSUE THREAD

**Issue by charleenfei** [centrifuge/tinlake-ui#325]

**Comment by denniswell** [comment]
Please find the text here: https://docs.google.com/document/d/185dRry8O2EaP-xR9Uh_LFzANS-yyArgn55r-FPICTLU/edit#heading=h.kgbs4tb2cl6k

**Comment by denniswell** [comment]
Image
![tinlake-logo_circle](https://user-images.githubusercontent.com/48755923/82119248-2115bb80-977d-11ea-961d-6988e6cbcfa0.png)
[tinlake-logo_circle.svg.zip](https://github.com/centrifuge/tinlake-ui/files/4638303/tinlake-logo_circle.svg.zip)
