### ISSUE TITLE
Improve Navbar Pool name resizing behaviour

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#379]
Pool name should stay in its initial position close to the Tinlake icon when Navbar switches to menu not move to the middle
![](https://storage.googleapis.com/centrifuge-hackmd/upload_e8f39fc1207bb0740c62c6b5569d302d.png)

**Comment by philipstanislaus** [comment]
Closing this as not worthwhile, as discussed with @denniswell
