### ISSUE TITLE
Redesign navbar

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/tinlake-ui#396]
### AC
- adjust header height
- add separators after Pool name and before connect button / details
- implement new resizing behaviour

More detailed specs:
https://centrifuge.hackmd.io/2srVnKmoRmGKWZTFFS6Lfg#ACs-Web3-Transaction-management
https://www.figma.com/file/EWziKt1qCFdHGhWdnkrcKf/Tinlake-UI?node-id=1030%3A1822

The following screenshot is taken at >1000px screen width yet the navigation doesn't fully fit. We should be able to make the header much shorter in height and use smaller font sizes to avoid having to use the hamburger menu

<img width="1170" alt="Screen Shot 2020-05-27 at 15 52 28" src="https://user-images.githubusercontent.com/31727/83028824-3b2f8380-a032-11ea-803d-9aebba35e71d.png">

----

All mockups here: https://www.figma.com/file/EWziKt1qCFdHGhWdnkrcKf/Tinlake-UI?node-id=1030%3A1822

#### (i) Design update
- See mockup for design, in particular, new height 56px
- Add separators between Tinlake logo, selected pools and tabs and tabs and wallet component
![](https://storage.googleapis.com/centrifuge-hackmd/upload_4cc5d51eaae84827d407d70a029ab516.png)

**Comment by philipstanislaus** [comment]
@denniswell could you coordinate that we get a good looking header height design for this ticket?  

Afterwards, can we have this as a bounty ticket?
