### ISSUE TITLE
Change Asset Originator and Issuer in Paperchain Overview

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#403]
Under **Pool Details**, both should be Paperchain Pilot LLC

**Comment by philipstanislaus** [comment]
@denniswell could you be a bit more specific where you want this changed? 

![Uploading Bildschirmfoto 2020-06-04 um 15.06.18.png…]()

Is the following change enough? 

```
Asset Originator: Paperchain Pilot LLC
Collateral: Music Streaming Invoices from Spotify
Average Invoice Size: $25,000
Maturity Date: 60 days invoices
Issuer: Paperchain Pilot LLC
```

**Comment by denniswell** [comment]
yes, Asset Originator and Issuer under pool details, so the following change is enough

![image](https://user-images.githubusercontent.com/48755923/83767451-f634ce00-a67d-11ea-9b2c-edb17bbe3f89.png)
