### ISSUE TITLE
Remove borrow/lending/loans terms

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#415]
This is due to legal reasons unfortunately
See all changes here (slides 1-4): https://docs.google.com/presentation/d/16BAIr2XDTCQO9rwz4rDPkU6Rn9UAOnXICUk9cXUaPMQ/edit#slide=id.g887d6fadc1_1_11

Guideline
Capitals in Headlines terms
DAI as Unit, Dai in text

**Comment by philipstanislaus** [comment]
Changed all the terms in your screenshots, searched the whole UI codebase for the terms in the table that are shown in error messages/success messages/buttons and replaced them, changed the URL paths `/loans/loan?loanId=...` to `/assets/asset?assetId=...`.

**Comment by philipstanislaus** [comment]
https://github.com/centrifuge/tinlake-ui/pull/421
