### ISSUE TITLE
Renaming of borrow/loans and other terms in code

### ISSUE THREAD

**Issue by philipstanislaus** [centrifuge/tinlake-ui#422]
We are using old terms like `loan` internally across repositories (tinlake.js around 100 occurances, tinlake-ui asound 430 occurance of the term loan alone). 

While we can use an IDE's/editor's rename feature to rename those relatively quickly, there are some negative consequences:

1. Renaming would break existing functions in tinlake.js. tinlake.js has functions such as `borrow`, `getProxyOwnerByLoan` or `canSetLoanPrice`. These functions will be called at some point by external parties – is that an issue? Do we have to rename the functions?
2. We need to re-index the subgraph, which takes some time.

The more adoption/usage of tinlake.js/indexed blocks in subgraph we have, the more annoying these breaking changes will be.

We need to decide whether we want to invest a few hours now to have consistent internal namings or whether we just stick with the old terms internally.

Open: 
- Which repositories need to be changed? tinlake.js, tinlake-ui, tinlake, tinlake-subgraph, ...?
- Which terms exactly do we want to use?

**Comment by offerijns** [comment]
Should be done after v2 pools are removed from the code (or rather, archived)
