### ISSUE TITLE
Kovan deployment update

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#436]
We may show the Kovan pools for Demos as well and thus need to:
(i) Align wording with Mainnet (Loan -->Asset)
(ii) UpdatePool names and describtions

Details here (https://docs.google.com/presentation/d/16BAIr2XDTCQO9rwz4rDPkU6Rn9UAOnXICUk9cXUaPMQ/edit#slide=id.g8a1883ea1c_0_0) from slide 2-6.

**Comment by philipstanislaus** [comment]
Done. Since this was a change of copy only, I pushed directly to `develop` without code review. The deployment is live: https://kovan.staging.tinlake.centrifuge.io/
