### ISSUE TITLE
Minor UI wording changes

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#467]
Landing Page/Dashboard: Remove Avg Fee Column
Several screens: Reword DROP Rate --> DROP APR
Pool Overview: Rename 'Invest' --> 'Learn more' button
Assets tab: Rename 'Finance asset' --> 'Open financing' button

See also screens [here (2-6)](https://docs.google.com/presentation/d/16BAIr2XDTCQO9rwz4rDPkU6Rn9UAOnXICUk9cXUaPMQ/edit#slide=id.g8a1883ea1c_0_18)

**Comment by lucasvo** [comment]
One more change: Remove add up loans outstanding and loans repaid into one box and call it "Assets Financed to Date" and "Total Active Financings" as "Assets Locked".

**Comment by denniswell** [comment]
To avoid any misunderstanding on the last point:
Table columns stay as they are (apart from dropping Avg fee column
Box "Ongoing Pools" is replaced with “Total Number of Pools” [aggregating closed + ongoing]
Box "Total Active Financings" can be dropped
Boxes "Total Outstanding Volume" and "Total Repaid Volume" should replaced with “Total Financed to Date” [showing sum of the current repaid & outstanding boxes]
