### ISSUE TITLE
Tx failure toast should include link to etherscan

### ISSUE THREAD

**Issue by philipstanislaus** [centrifuge/tinlake-ui#475]
This would be helpful for debugging/investigating what failed.

Currently, it looks like this: 

<img width="372" alt="Bildschirmfoto 2020-08-25 um 10 36 31" src="https://user-images.githubusercontent.com/6912756/91152187-f366d980-e6be-11ea-8589-69e580c5b5e3.png">

**Comment by philipstanislaus** [comment]
Can we also show the error that is shown on Etherscan directly? 

<img width="970" alt="Bildschirmfoto 2020-08-25 um 10 40 51" src="https://user-images.githubusercontent.com/6912756/91152633-81db5b00-e6bf-11ea-884f-883a86625d96.png">

**Comment by offerijns** [comment]
Currently we don't properly return the errors from Tinlake.js, but I'm trying to improve that during the Tinlake.js rewrite to Ether.js, so then we definitely should definitely be able to show better errors.

**Comment by offerijns** [comment]
I just checked, the reason we're not showing an Etherscan link is similar: Tinlake.js doesn't return the tx hash if a tx fails.. Luckily the Tinlake.js rewrite is already underway, so I'd suggest waiting to fix this issue until the rewrite is done.

**Comment by philipstanislaus** [comment]
Sounds good, thanks 🙏
