### ISSUE TITLE
Minor `upcoming pools` follow ups plus other minor UI updates

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#489]
`Upcoming pools` follow up.

(i) Sort Dashboard Pool Overview table after column Status: Upcoming --> Open --> closed. If possible pools within open should be ordered by outstanding DAI (not must have)
(ii) Set Kickfurther Drop rate = 10.00%, Min TIn = 20.00%
(iii) Update bottom of to Kickfurther AO/Pool Details:
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/aff9fbd5-0198-4368-8514-8d3bf27c3bd9)
Remove "Contact the asset originator"
Make bold "Interested in learning more?"
Add Discord link: "Kickfurther's Discourse", https://discourse.centrifuge.io/t/community-introduction-kickfurther/218 
kickfurther.com
bizdev@centrifuge.io

Others:
(i) Order the pools in the the Nav bar drop down alphabetically
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/f80f126d-3e6c-4af1-bd29-2f2c02644c64)
(ii) Update wording in Investment modal:
Current: "To invest in this pool please provide your information to go through KYC. Submit your information below to start the KYC and onboarding process. The Issuer will shortly reach out to you." 
Replace with: "If you want to learn more please leave your contact details and investor profile to start on-boarding. Please note that this is for non-US investors and accredited US investors only."
(iii) Change investment size in `Investment size` dropdown to: <10,000 USD, 10,000-24,999 USD, 25,000-50,000 USD, >50,000 USD
(iiii) Change wording of 'Learn more' button on Overview tab to 'Get started'

**Comment by philipstanislaus** [comment]
(iv) Fix redirects (they currently work locally with `npm start`, but not on netlify?)

**Comment by philipstanislaus** [comment]
(v) Kickfurther pool is not counted in number of pools on Dashboard (not a must, if complex to implement, but would be good)

**Comment by philipstanislaus** [comment]
All done except (iv) and (v) in #490
