### ISSUE TITLE
Investigate potential state issue with investment transactions

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#492]
Alina invested in PC2 yesterday and mentioned that there seems to be a state error in the UI. After a successful transaction the UI did not show her updated token balance and 0 investment limit, but still the old state with 0 token balance and the allocated investment limit. One other investor had reported similar. 

I was able to replicate on Kovan, so it indeed does not seem to be a timing issue:

Wrong Screen after successful transaction
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/e89e6e1b-ea22-4880-8d1e-763394f5dc26)

Correct Screen after reload
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/351aabce-88b2-413f-ac1f-7c8a8849b91f)

**Comment by offerijns** [comment]
@denniswell I found the reason for this bug, will address the fix along with the Tinlake.js rewrite update.

**Comment by denniswell** [comment]
Great, thanks
