### ISSUE TITLE
Handle Fixed Fees / Partial repay in the UI

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#510]
**Background:**
Kickfurther our first revolving pool doesn't have a financing fee that accrues interest, but a fixed fee/margin on top of the Principal. E.g. Borrow 100, fixed fee 20% --> Debt =120 regardless of the point in time. Then repayments happen in installments, e.g. 3 x 40. So, Debt would be reduced to 80, 40, 0 with every repayment. This is implemented in the contracts already. The fixed fee is not set in the scorecard at deployment but can be set in the pile per risk class. For the Kickfurther use case (which only has the fixed fee) the financing fee in scorecard for the risk class needs to be set to ONE (so the interest rate is 0).

**What needs to be done**
**MVP - Enable partial repayments in UI**
Currently we only allow one-time bullet repayments of the total Debt in the UI (for repayment the UI takes current debt and doesnt allow user to change the input0. For Kickfurther we would also need to allow partial repayments. Ideally we would only allow this for fixed fee pools so that bullet repayments remain the only option for other use cases. This could be done by setting a flag in the Pool config "FixedFee=yes". Only in this case, partial repayment would be enabled.

Partial Repayment flow
- Check Borrower address connected
- Repay button active, Input field active, default value 0.0000
- User inputs repayment amount
- User confirms transaction in Metamask
- Outstanding Debt is reduced by repayment amount
- Repay button active, Input field active remain active for further repayments

**v0.1 - Improve UI/UX**
If the flag FixedFee=yes is set in the pool config, the "Financing Fee" field and column could be replaced by a "Fixed Fee" field/column which shows the Fixed Fee instead of the Financing Fee. This would need to be replaced in:
- Asset Details - Field replaced
- Asset List (on Overview and Asset tab) - Column replaced

**Comment by philipstanislaus** [comment]
Thanks. This has been addressed in https://github.com/centrifuge/tinlake-pool-config/pull/25 and https://github.com/centrifuge/tinlake-ui/pull/513 with 2 small deviations: 

Default value in repayment input field is the remaining total debt and the variable is called `partialRepay`.
