### ISSUE TITLE
v3 RevPool - Problem with Edge Case Max Reserve amount < than current reserve

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#527]
Background: I tried an edge case, with Max Reserve amount < than current reserve.

First the close epoch transaction was stuck in UI
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/766b5d96-0163-4287-90fa-53219648840c)
Transaction in Metamask was succesful though. 
https://kovan.etherscan.io/tx/0xf452df4661e3d9f91535510762a858ff41c407bde1baaa058c7e54bf107fa016

After reload everything seemed fine though. But when I wanted to cancel my order, it failed

https://kovan.etherscan.io/tx/0xc89e10164b7a9d90b9c4181d9376cbc7eddee5f4417d490ace38703ce74025b2
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/52790cee-7fc9-43d7-b302-e2217423e17c)

Now, I cannot close the epoch anymore
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/3a466b59-aa18-48d5-93b1-fd34bdfe089d)

**Comment by offerijns** [comment]
For reference, disburse with this user also fails: https://kovan.etherscan.io/tx/0xa6bf0d75f559e782c1b6830456048b304583d45c8d6fa0a7d0d9e6d2efec7cb2

Executed using `seth send 0x585da7133A5dFAE67482cDA5bbBf8b2f33CC1053 'disburse()()' `
