### ISSUE TITLE
Improve Fixed Fee Display in UI

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#531]
The fixed fee MVP (See [pull #25](https://github.com/centrifuge/tinlake-pool-config/pull/25), [pull #513](https://github.com/centrifuge/tinlake-ui/pull/513)

Background:
Kickfurther our first revolving pool doesn't have a financing fee that accrues interest, but a fixed fee/margin on top of the Principal. E.g. Borrow 100, fixed fee 20% --> Debt =120 regardless of the point in time. Then repayments happen in installments, e.g. 3 x 40. So, Debt would be reduced to 80, 40, 0 with every repayment. This is implemented in the contracts already. The fixed fee is not set in the scorecard at deployment but can be set in the pile per risk class. The MVP ([#510](https://github.com/centrifuge/tinlake-ui/issues/510)) enabled the UI to handle partial repayments in UI. The fixed fee approach should now also be correctly in the UI:

Implementation:
If the flag FixedFee=yes is set in the pool config, the "Financing Fee" field and column could be replaced by a "Fixed Fee" field/column which shows the Fixed Fee instead of the Financing Fee. This would need to be replaced in:
Asset Details - Field replaced
Asset List (on Overview and Asset tab) - Column replaced

**Comment by offerijns** [comment]
We don't currently have a fixed fee pool, so it's parked for that reason.
