### ISSUE TITLE
Copy & Paste icon should be the same everywhere

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/tinlake-ui#545]
<img width="1217" alt="Screen Shot 2020-10-14 at 18 11 38" src="https://user-images.githubusercontent.com/31727/96016252-d0e47780-0e48-11eb-8a89-0ec3e7905139.png">

Let's use the round one everywhere

**Comment by denniswell** [comment]
Should we also use dashed version for the back layer in the new style![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/024bd482-327e-4f57-85e9-86a08f0790f9)?
