### ISSUE TITLE
Add multiple addresses to memberlist

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#582]
Still TBD
Can be comma-seperated list, Component should realize whether one or multiple addresses

**Comment by lucasvo** [comment]
No, we should not add a third button. It's perfectly fine to use the same UI for adding one or multiple addresses. The code can then decide whether to use the call that adds multiple or single ones.

As for how addresses should be entered, I think ideally we have a single input where addresses can be entered either comma or space or new line separated. I would suggest we turn this UI element into a bounty.

I don't think we should implement remove for now until we need it.
