### ISSUE TITLE
UI picking up wrong DROP APR?

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#590]
In a call with an AO, looking at Tinlake, the AO’s browser (Chrome) was not showing a grey box instead of the DROP APR but already 11% which was replaced by 8% with the other grey boxes disappearing. He clicked on the details of CF3 before. I was not able to repeat it…

**Comment by hieronx** [comment]
This is likely fixed by multicall. Let's reopen if it occurs again.
