### ISSUE TITLE
Expose multiple repay in UI

### ISSUE THREAD

**Issue by denniswell** [centrifuge/tinlake-ui#597]
We will have several use cases soon for pools that require multiple repayments per asset
Currently the UI only allows one (full) repayment
Contracts also already allow multiple repayments
Pre-filled value of repayment component should be the Outstanding
Underline still Outstanding with setMax setting the outstanding
Fully repaid (=closed) is when the outstanding/max amount is repaid

**Comment by denniswell** [comment]
Update: We'll generally expose it, no pool flag

**Comment by philipstanislaus** [comment]
This is already implemented, actually. Could you test again @denniswell ?
